---
replicaCount: 3

image:
  repository: 345156409809.dkr.ecr.eu-west-1.amazonaws.com/plt.test
  pullPolicy: IfNotPresent
  tag: test1

ingress:
  className: "kong"
  paths:
    - path: /mywebapp
      pathType: Prefix
  annotations:
    konghq.com/strip-path: "true"

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 150m
    memory: 100Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85

container:
  env:
    GREET_VAR: "world"
