name: Build and Pack

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      region: eu-west-1
      docker-ecr-repository: ecr-docker-dev-eu-west-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.region }}

      - name: Push to ECR
        id: tag
        run: |
          aws ecr get-login-password --region ${{ env.region }}  | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.region }}.amazonaws.com
          docker build -f app/Dockerfile --tag ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.region }}.amazonaws.com/${{ env.docker-ecr-repository }}:$GITHUB_SHA .

          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.region }}.amazonaws.com/${{ env.docker-ecr-repository }}:$GITHUB_SHA
      
      - name: Install helm cli
        uses: azure/setup-helm@v1
        with:
          version: '3.8.0'

      - name: Install yq
        uses: mikefarah/yq@master

      - name: Update values.yml for mywebapp
        run: |
          yq eval -i '.image.tag|= "$GITHUB_SHA"' helm/mywebapp/values.yaml

      - name: Package helm chart
        run: |
          helm package helm/mywebapp

      - name: Login to ECR
        run: |
          aws ecr get-login-password \
          --region ${{ env.region }} | helm registry login \
          --username AWS \
          --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.region }}.amazonaws.com
      
      - name: Push helm chart to ECR
        run: |
          package=$(ls *.tgz)
          helm push $package oci://${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.region }}.amazonaws.com
